### ISSUE TITLE
백준 10818 속도 개선에 대해서

### ISSUE THREAD

**Issue by yuseon-lim** [yuseon-Lim/algorithm-study#3]
하임, [최대 최소 문제](https://github.com/yuseon-Lim/algorithm-study/blob/main/haim/boj-10818.py)

말인데, 매번 if문을 한번씩 검사하면 시간적으로 낭비가 있을거같음
```
    if (cnt == 0):
        min = i
        max = i
```
이부분

나는 `sys`모듈에서 `sys.maxsize` 이용해서 max엔 최솟값, min엔 최댓값으로 초기화하고 시작했는데, 더 좋은 방법 있을까낭?

**Comment by yuseon-lim** [comment]
[이거보면](https://m.blog.naver.com/PostView.nhn?isHttpsRedirect=true&blogId=wpghks7&logNo=221616765020&categoryNo=4&proxyReferer=) 삼성에서는 제한하는거같음

삼성 코테가 아니라면 sys모듈은 입출력 관련해서도 성능 향상 할 수 있어서
제한이 없다면 쓰는것도 좋을듯 함 내생각~

**Comment by hyou55** [comment]
오홍 알겠습니당
